/**
 * API de gestion des utilisateurs, roles et produits
 * Documentation du microservices de la gestion des utilisateurs,roles et produits
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProduitDTO } from './produitDTO';


export interface AppUserDTO { 
    /**
     * Fonctionnel id of the classe
     */
    idUser?: number;
    /**
     * the name of the user
     */
    nom?: string;
    /**
     * the firstName of the user
     */
    prenom?: string;
    /**
     * the email of the user
     */
    email?: string;
    /**
     * the password of the user
     */
    password?: string;
    /**
     * the state of the user
     */
    etat?: number;
    produits?: Array<ProduitDTO>;
}

