springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8080
  servlet:
    context-path: /backend-admin/api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin-db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  application:
    name: spring-backend-admin

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  info:
    application:
      name: backend-admin
      version: '@project.version@'